aliases:
  All Beauty: ["All Beauty", "Beauty", "Beauty and Personal Care"]
  Electronics: ["Electronics", "Consumer Electronics"]
  Books: ["Books", "Literature", "Reading"]
  Home and Kitchen: ["Home & Kitchen", "Home and Kitchen", "Kitchen & Dining"]

hierarchy:
  All Beauty:
    - Skincare
    - Hair Care
    - Makeup
  Electronics:
    - Audio & Video
    - Computers
    - Accessories
  Books:
    - Fiction
    - Non-fiction
    - Children's Books
  Home and Kitchen:
    - Kitchen & Dining
    - Furniture
    - Home Décor
